#!/bin/sh

chown -v root:root /opt/bin/kamailio-webrtc
chown -v root:root /etc/init.d/kamailio-webrtc
chown -v root:root /etc/default/kamailio-webrtc

# Automatically added by dh_installinit
if [ -x "/etc/init.d/kamailio-webrtc" ]; then
    if [ ! -e "/etc/init/kamailio-webrtc.conf" ]; then
        update-rc.d asterisk-sidecar defaults >/dev/null
    fi
    invoke-rc.d asterisk-sidecar start || exit $?
fi
