#!/bin/sh
set -e

# Automatically added by dh_installinit
if [ "$1" = install ] || [ "$1" = upgrade ]; then
	if [ -e "/etc/init.d/kamailio-webrtc" ] && [ ! -L "/etc/init.d/$PKG_NAME" ]; then
		if [ "`md5sum \"/etc/init.d/kamailio-webrtc\" | sed -e \"s/ .*//\"`" != \
		     "`dpkg-query -W -f='${Conffiles}' kamailio-webrtc | sed -n -e \"\\\\' /etc/init.d/kamailio-webrtc '{s/ obsolete\$//;s/.* //p}\"`" ]
		then
			echo "Obsolete conffile /etc/init.d/kamailio-webrtc has been modified by you, renaming to .dpkg-bak"
			mv -f "/etc/init.d/kamailio-webrtc" "/etc/init.d/kamailio-webrtc.dpkg-bak"
		else
			rm -f "/etc/init.d/kamailio-webrtc"
		fi
	fi
fi
# End automatically added section
